M48
; DRILL file {KiCad 7.0.1-3b83917a11~172~ubuntu20.04.1} date Thu 16 Mar 2023 09:37:27 PM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-16T21:37:27-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-3b83917a11~172~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X142.189Y-71.069
X154.991Y-71.069
T0
M30
